import{detectIntent,extractDepartmentName,extractTemperature}from'./chatbotIntentService.js';import{healthInformation,safeHelp}from'./chatbotSafetyService.js';import{chatbotToolService}from'./chatbotToolService.js';
const contexts=new Map();const days={SUNDAY:0,MONDAY:1,TUESDAY:2,WEDNESDAY:3,THURSDAY:4,FRIDAY:5,SATURDAY:6};const time=value=>new Date(value).toLocaleTimeString('en-GH',{hour:'numeric',minute:'2-digit',timeZone:'UTC'});const nextDate=day=>{const date=new Date(),target=days[day?.toUpperCase()];if(target===undefined)return date.toISOString().slice(0,10);let delta=(target-date.getDay()+7)%7;if(!delta)delta=7;date.setDate(date.getDate()+delta);return date.toISOString().slice(0,10);};
export async function respondToPatient({message,hospitalId,date,auth,patient,request},dependencies={}){const tools=dependencies.tools||chatbotToolService,previous=contexts.get(auth.userId)||{},context={...previous,...(hospitalId?{hospitalId}:{}),...(date?{date}:{})};const intent=detectIntent(message,context);let data=null,response='';
if(intent==='HOSPITAL_LIST'){data=await tools.hospitals();response=data.length?`Active hospitals: ${data.map(x=>x.name).join(', ')}.`:'No active hospitals are currently listed.';}
else if(intent==='DEPARTMENT_LIST'){if(!context.hospitalId)return{intent,response:'Please select a hospital first.',data:null,context};data=await tools.departments(context.hospitalId);response=data.length?`Available departments: ${data.map(x=>x.name).join(', ')}.`:'No active departments are currently listed.';}
else if(['DEPARTMENT_SCHEDULE','DOCTOR_AVAILABILITY','BOOK_APPOINTMENT'].includes(intent)){if(!context.hospitalId)return{intent,response:'Please select a hospital first so I can use its real schedule.',data:null,context};const name=extractDepartmentName(message,context.departmentName);const department=name?await tools.departmentByName(context.hospitalId,name):null;if(!department)return{intent,response:'Please name a department available at the selected hospital.',data:null,context};context.departmentId=department.id;context.departmentName=department.name;if(intent==='DEPARTMENT_SCHEDULE'){data=department.schedules;response=data.length?`${department.name} currently operates ${data.map(x=>`${x.dayOfWeek} ${time(x.startTime)}–${time(x.endTime)}`).join('; ')}.`:`${department.name} has no active clinic schedule.`;}else{const targetDate=context.date||nextDate((message.match(/monday|tuesday|wednesday|thursday|friday|saturday|sunday/i)||[])[0]);data=await tools.doctors(department.id,targetDate);context.date=targetDate;response=data.length?`${data.length} doctor option(s) have real available slots on ${targetDate}. Select Book to review and confirm in the booking workflow.`:`No available ${department.name} slots were found on ${targetDate}.`;}}
else if(intent==='MY_APPOINTMENTS'){data=await tools.appointments(patient.id);response=data.length?`You have ${data.length} appointment record(s). Your nearest active appointment is ${data.find(x=>!['CANCELLED','COMPLETED','MISSED'].includes(x.status))?.appointmentNumber||'not currently scheduled'}.`:'You have no appointment records.';}
else if(intent==='CARD_STATUS'){data=await tools.cards(patient.id);response=data.length?data.map(x=>`${x.cardType.replace('_',' ')} ${x.maskedCardNumber}: ${x.verificationStatus}`).join('; '):'You have no linked cards.';}
else if(intent==='SYMPTOM_CHECK'){if(!context.hospitalId)return{intent,response:'Please select a hospital before starting a symptom assessment.',data:null,context};const temperature=extractTemperature(message);data=await tools.assess(patient,auth.userId,{hospitalId:context.hospitalId,symptomsText:message,symptoms:[],severity:temperature>=39?'MODERATE':'MILD',pregnancyStatus:false,temperature},request);response=`Suggested urgency: ${data.urgency}. ${data.explanation} ${data.recommendedAction} ${data.disclaimer}`;}
else if(intent==='GENERAL_HEALTH_INFO')response=healthInformation(message);else response=safeHelp();contexts.set(auth.userId,{hospitalId:context.hospitalId,departmentId:context.departmentId,departmentName:context.departmentName,date:context.date});return{intent,response,data,context,requiresConfirmation:intent==='BOOK_APPOINTMENT'};}
export const chatbotService={respond:respondToPatient,clearContext:userId=>contexts.delete(userId)};
