import { useEffect, useState } from 'react';
import { Activity, Bell, Brain, CalendarDays, CreditCard, HeartPulse, Home, LogOut, PlusCircle, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { appointmentService } from '../services/appointmentService';
import { patientCardService } from '../services/patientCardService';
import MobileBottomNavigation from '../components/patient/MobileBottomNavigation';
import OfflineBanner from '../components/patient/OfflineBanner';
import InstallPwaPrompt from '../components/patient/InstallPwaPrompt';
import BookAppointmentPage from './patient/BookAppointmentPage';
import AppointmentsPage from './patient/AppointmentsPage';
import PatientCardsPage from './patient/PatientCardsPage';
import NotificationsPage from './patient/NotificationsPage';
import PatientProfilePage from './patient/PatientProfilePage';
import PatientVitalsPage from './patient/PatientVitalsPage';
import SymptomAssessmentPage from './patient/SymptomAssessmentPage';
const NAV = [['home',Home,'Home'],['symptoms',Brain,'Symptom Check'],['book',PlusCircle,'Book Appointment'],['appointments',CalendarDays,'Appointments'],['vitals',Activity,'My Vitals'],['cards',CreditCard,'My Cards'],['notifications',Bell,'Notifications'],['profile',UserRound,'Profile']];
function PatientHome({ user, onSelect, refreshKey }) { const [appointments,setAppointments]=useState([]),[cards,setCards]=useState([]); useEffect(()=>{appointmentService.list().then(r=>setAppointments(r.data)).catch(()=>{});patientCardService.list().then(r=>setCards(r.data)).catch(()=>{});},[refreshKey]); const next=appointments.find(x=>!['CANCELLED','COMPLETED','MISSED'].includes(x.status)); return <section className="patient-panel"><div className="patient-hero"><HeartPulse/><div><p>Welcome back</p><h2>{user?.profile?.firstName || user?.firstName || 'Patient'}</h2></div></div><div className="summary-grid"><button onClick={()=>onSelect('appointments')}><span>Next appointment</span><strong>{next ? `${new Date(next.appointmentDate).toLocaleDateString()} · ${next.status.replaceAll('_',' ')}` : 'None booked'}</strong></button><button onClick={()=>onSelect('cards')}><span>Verified cards</span><strong>{cards.filter(x=>x.verificationStatus==='VERIFIED').length}</strong></button><button onClick={()=>onSelect('vitals')}><span>Clinical records</span><strong>My vitals</strong></button></div><button className="quick-book" onClick={()=>onSelect('book')}><PlusCircle/> Book an appointment</button><div className="future-note"><h3>Coming in Phase 7</h3><p>AI-assisted symptom assessment is not active yet.</p></div></section> }
export default function PatientDashboard(){const {user,logout}=useAuth();const [tab,setTab]=useState('home'),[refreshKey,setRefreshKey]=useState(0),[bookingPrefill,setBookingPrefill]=useState(null);const booked=(target)=>{setRefreshKey(x=>x+1);if(target)setTab(target)};const bookAssessment=result=>{setBookingPrefill({hospitalId:result.recommendedDepartment?.hospitalId,departmentId:result.recommendedDepartment?.id,assessmentId:result.id});setTab('book')};return <div className="patient-app"><OfflineBanner/><aside className="patient-sidebar"><div className="patient-brand"><HeartPulse/> CareSync</div><nav>{NAV.map(([key,Icon,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={19}/>{label}</button>)}</nav><InstallPwaPrompt/><button className="logout" onClick={logout}><LogOut size={18}/>Log out</button></aside><main className="patient-main"><header><div><small>Secure patient portal</small><h1>{NAV.find(x=>x[0]===tab)?.[2]}</h1></div><button className="notification-button" aria-label="Open notifications" onClick={()=>setTab('notifications')}><Bell/></button></header>{tab==='home'&&<PatientHome user={user} onSelect={setTab} refreshKey={refreshKey}/>} {tab==='symptoms'&&<SymptomAssessmentPage onBook={bookAssessment}/>} {tab==='book'&&<BookAppointmentPage initialSelection={bookingPrefill} openCards={()=>setTab('cards')} onBooked={booked}/>} {tab==='appointments'&&<AppointmentsPage refreshKey={refreshKey}/>} {tab==='vitals'&&<PatientVitalsPage/>} {tab==='cards'&&<PatientCardsPage/>} {tab==='notifications'&&<NotificationsPage/>} {tab==='profile'&&<PatientProfilePage/>}</main><MobileBottomNavigation active={tab} onSelect={setTab}/></div>}
