import { Router } from 'express';
import { adminController } from '../controllers/adminController.js';
import { authenticate, requireRole } from '../middleware/authenticate.js';
import { validate } from '../middleware/validate.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { createDoctorAccountSchema, createNurseAccountSchema, updateDoctorProfileSchema } from '../validators/staffValidators.js';
import { doctorScheduleSchema, generateSlotsSchema, scheduleExceptionSchema } from '../validators/scheduleValidators.js';
import { z } from 'zod';
import { uuid } from '../validators/commonValidators.js';
import { managementScheduleController } from '../controllers/managementScheduleController.js';
import { updateHospitalSchema } from '../validators/hospitalValidators.js';
import { createDepartmentSchema } from '../validators/departmentValidators.js';
import { departmentScheduleSchema } from '../validators/scheduleValidators.js';
import { reviewCorrectionController } from '../controllers/reviewCorrectionController.js';
import { bulkStaffSchema, nurseAppointmentSchema, nurseDepartmentSchema, reportQuerySchema } from '../validators/reviewCorrectionValidators.js';

const router = Router();
router.use(authenticate, requireRole('ADMIN'));
router.get('/hospital', asyncHandler(adminController.hospital));
router.patch('/hospital', validate({ body: updateHospitalSchema }), asyncHandler(adminController.updateHospital));
router.get('/departments', asyncHandler(adminController.departments));
router.post('/departments', validate({ body: createDepartmentSchema }), asyncHandler(adminController.createDepartment));
router.post('/departments/:departmentId/schedules', validate({ params: z.object({ departmentId: uuid }), body: departmentScheduleSchema.omit({ hospitalId: true, departmentId: true }) }), asyncHandler(adminController.createDepartmentSchedule));
router.post('/doctors', validate({ body: createDoctorAccountSchema }), asyncHandler(adminController.createDoctor));
router.get('/doctors', asyncHandler(adminController.listDoctors));
router.patch('/doctors/:doctorId', validate({ params: z.object({ doctorId: uuid }), body: updateDoctorProfileSchema }), asyncHandler(adminController.updateDoctor));
router.post('/doctors/:doctorId/departments', validate({ params: z.object({ doctorId: uuid }), body: z.object({ departmentId: uuid, primaryDepartment: z.boolean().optional().default(false) }) }), asyncHandler(adminController.assignDepartment));
router.delete('/doctors/:doctorId/departments/:departmentId', validate({ params: z.object({ doctorId: uuid, departmentId: uuid }) }), asyncHandler(adminController.removeDepartment));
router.post('/doctors/:doctorId/schedules', validate({ params: z.object({ doctorId: uuid }), body: doctorScheduleSchema.omit({ doctorId: true, hospitalId: true }) }), asyncHandler(adminController.createDoctorSchedule));
router.get('/doctors/:doctorId/exceptions', validate({ params: z.object({ doctorId: uuid }) }), asyncHandler(managementScheduleController.listExceptions));
router.post('/doctors/:doctorId/exceptions', validate({ params: z.object({ doctorId: uuid }), body: scheduleExceptionSchema }), asyncHandler(managementScheduleController.createException));
router.post('/doctors/:doctorId/generate-slots', validate({ params: z.object({ doctorId: uuid }), body: generateSlotsSchema }), asyncHandler(managementScheduleController.generate));
router.post('/nurses', validate({ body: createNurseAccountSchema }), asyncHandler(adminController.createNurse));
router.get('/nurses', asyncHandler(reviewCorrectionController.nurses));
router.patch('/nurses/:nurseId/departments', validate({ params: z.object({ nurseId: uuid }), body: nurseDepartmentSchema }), asyncHandler(reviewCorrectionController.assignDepartment));
router.patch('/appointments/:appointmentId/nurse', validate({ params: z.object({ appointmentId: uuid }), body: nurseAppointmentSchema }), asyncHandler(reviewCorrectionController.assignAppointment));
router.get('/appointments', validate({ query: reportQuerySchema }), asyncHandler(reviewCorrectionController.appointments));
router.get('/analytics', asyncHandler(reviewCorrectionController.analytics));
router.get('/reports', validate({ query: reportQuerySchema }), asyncHandler(reviewCorrectionController.report));
router.post('/staff/bulk-import', validate({ body: bulkStaffSchema }), asyncHandler(reviewCorrectionController.bulk));
export default router;
