import { Router } from 'express';
import { clinicalController as controller } from '../controllers/clinicalController.js';
import { authenticate, requireAnyRole, requireRole } from '../middleware/authenticate.js';
import { validate } from '../middleware/validate.js';
import { idParamsSchema } from '../validators/commonValidators.js';
import { clinicalVitalSchema, triageSchema, consultationDraftSchema, consultationCompleteSchema } from '../validators/clinicalValidators.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { symptomAssessmentController } from '../controllers/symptomAssessmentController.js';
const router=Router();router.use(authenticate);
router.get('/nurse/appointments/today',requireRole('NURSE'),asyncHandler(controller.nurseWorklist));
router.get('/nurse/assigned-patients',requireRole('NURSE'),asyncHandler(controller.nurseAssigned));
router.get('/nurse/queue',requireRole('NURSE'),asyncHandler(controller.nurseWorklist));
router.patch('/appointments/:id/check-in',requireAnyRole('NURSE','ADMIN'),validate({params:idParamsSchema}),asyncHandler(controller.checkIn));
router.get('/appointments/:id/vitals',requireAnyRole('NURSE','DOCTOR'),validate({params:idParamsSchema}),asyncHandler(controller.vitals));
router.post('/appointments/:id/vitals',requireAnyRole('NURSE','DOCTOR'),validate({params:idParamsSchema,body:clinicalVitalSchema}),asyncHandler(controller.recordVitals));
router.patch('/vitals/:id/verify',requireRole('NURSE'),validate({params:idParamsSchema}),asyncHandler(controller.verifyVital));
router.post('/appointments/:id/triage',requireRole('NURSE'),validate({params:idParamsSchema,body:triageSchema}),asyncHandler(controller.triage));
router.patch('/appointments/:id/waiting',requireRole('NURSE'),validate({params:idParamsSchema}),asyncHandler(controller.waiting));
router.get('/doctors/me/queue',requireRole('DOCTOR'),asyncHandler(controller.doctorQueue));
router.get('/doctors/me/appointments/:id/clinical',requireRole('DOCTOR'),validate({params:idParamsSchema}),asyncHandler(controller.context));
router.patch('/doctors/me/appointments/:id/start',requireRole('DOCTOR'),validate({params:idParamsSchema}),asyncHandler(controller.start));
router.patch('/doctors/me/appointments/:id/consultation',requireRole('DOCTOR'),validate({params:idParamsSchema,body:consultationDraftSchema}),asyncHandler(controller.save));
router.patch('/doctors/me/appointments/:id/complete',requireRole('DOCTOR'),validate({params:idParamsSchema,body:consultationCompleteSchema}),asyncHandler(controller.complete));
router.get('/appointments/:id/symptom-assessment',requireAnyRole('NURSE','DOCTOR'),validate({params:idParamsSchema}),asyncHandler(symptomAssessmentController.clinical));
export default router;
