import { Router } from 'express';
import { z } from 'zod';
import { patientSelfServiceController as controller } from '../controllers/patientSelfServiceController.js';
import { authenticate, requireRole } from '../middleware/authenticate.js';
import { validate } from '../middleware/validate.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { idParamsSchema, uuid } from '../validators/commonValidators.js';
import { createPatientCardSchema } from '../validators/patientCardValidators.js';
import { availabilitySchema, cancellationSchema, patientBookingSchema, patientProfileUpdateSchema, recommendationSchema, rescheduleSchema } from '../validators/patientSelfServiceValidators.js';
import { clinicalController } from '../controllers/clinicalController.js';
import { symptomAssessmentController } from '../controllers/symptomAssessmentController.js';
import { createSymptomAssessmentSchema } from '../validators/symptomAssessmentValidators.js';
import { symptomRateLimiter } from '../middleware/symptomRateLimiter.js';
import { chatbotController } from '../controllers/chatbotController.js';

const router = Router();
router.use(authenticate, requireRole('PATIENT'));
router.get('/hospitals', asyncHandler(controller.hospitals));
router.get('/departments', asyncHandler(controller.careSyncDepartments));
router.get('/hospitals/:hospitalId/departments', validate({ params: z.object({ hospitalId: uuid }) }), asyncHandler(controller.departments));
router.get('/departments/:departmentId/availability', validate({ params: z.object({ departmentId: uuid }) }), asyncHandler(controller.availability));
router.get('/departments/:departmentId/doctors', validate({ params: z.object({ departmentId: uuid }), query: availabilitySchema.partial() }), asyncHandler(controller.doctors));
router.get('/recommendation', validate({ query: recommendationSchema }), asyncHandler(controller.recommend));
router.post('/appointments', validate({ body: patientBookingSchema }), asyncHandler(controller.book));
router.get('/appointments', asyncHandler(controller.appointments));
router.get('/appointments/:id', validate({ params: idParamsSchema }), asyncHandler(controller.appointment));
router.patch('/appointments/:id/cancel', validate({ params: idParamsSchema, body: cancellationSchema }), asyncHandler(controller.cancel));
router.patch('/appointments/:id/reschedule', validate({ params: idParamsSchema, body: rescheduleSchema }), asyncHandler(controller.reschedule));
router.get('/cards', asyncHandler(controller.cards));
router.post('/cards', validate({ body: createPatientCardSchema }), asyncHandler(controller.createCard));
router.get('/profile', asyncHandler(controller.profile));
router.patch('/profile', validate({ body: patientProfileUpdateSchema }), asyncHandler(controller.updateProfile));
router.get('/notifications', asyncHandler(controller.notifications));
router.patch('/notifications/read-all', asyncHandler(controller.readAllNotifications));
router.patch('/notifications/:id/read', validate({ params: idParamsSchema }), asyncHandler(controller.readNotification));
router.get('/vitals', asyncHandler(clinicalController.patientVitals));
router.get('/appointments/:id/progress', validate({ params: idParamsSchema }), asyncHandler(clinicalController.progress));
router.get('/consultations/:id', validate({ params: idParamsSchema }), asyncHandler(clinicalController.patientConsultation));
router.post('/symptom-assessments', symptomRateLimiter, validate({ body: createSymptomAssessmentSchema }), asyncHandler(symptomAssessmentController.create));
router.get('/symptom-assessments', asyncHandler(symptomAssessmentController.list));
router.get('/symptom-assessments/:id', validate({ params: idParamsSchema }), asyncHandler(symptomAssessmentController.get));
router.post('/care-assistant/message', symptomRateLimiter, validate({ body: z.object({ message: z.string().trim().min(1).max(2000), hospitalId: uuid.optional(), date: z.iso.date().optional() }).strict() }), asyncHandler(chatbotController.message));
export default router;
