import { useEffect, useState } from 'react';
import { appointmentService } from '../../services/appointmentService';
import { patientService } from '../../services/patientService';
import StatusBadge from '../../components/patient/StatusBadge';
const fmt = value => new Date(value).toLocaleDateString(); const clock = value => new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', timeZone: 'UTC' });
export default function AppointmentsPage({ refreshKey = 0 }) {
 const [items,setItems]=useState([]),[error,setError]=useState(''),[selected,setSelected]=useState(null),[filter,setFilter]=useState('upcoming');
 const load=()=>appointmentService.list().then(r=>setItems(r.data)).catch(e=>setError(e.message)); useEffect(load,[refreshKey]);
 const cancel=async item=>{const reason=prompt('Optional cancellation reason')||undefined;try{await appointmentService.cancel(item.id,reason);load()}catch(e){setError(e.message)}};
 const reschedule=async item=>{const date=prompt('Enter a new clinic date (YYYY-MM-DD)');if(!date)return;try{const r=await patientService.doctors(item.department.id,date);const slots=r.data.flatMap(d=>d.appointmentSlots.map(s=>({...s,doctor:d})));if(!slots.length)return setError('No available slots on that date.');const choices=slots.map((s,i)=>`${i+1}. Dr. ${s.doctor.firstName} ${s.doctor.lastName} - ${clock(s.startTime)}`).join('\n');const choice=Number(prompt(`Choose a slot number:\n${choices}`))-1;if(!slots[choice])return setError('No slot was selected.');await appointmentService.reschedule(item.id,slots[choice].id);load()}catch(e){setError(e.message)}};
 const visible=items.filter(x=>filter==='cancelled'?x.status==='CANCELLED':filter==='past'?['COMPLETED','MISSED'].includes(x.status)||new Date(x.appointmentDate)<new Date().setHours(0,0,0,0):!['CANCELLED','COMPLETED','MISSED'].includes(x.status));
 return <section className="patient-panel"><h2>My appointments</h2>{error&&<p className="patient-error">{error}</p>}<div className="filter-tabs">{['upcoming','past','cancelled'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="appointment-list">{visible.map(item=><article key={item.id} className="appointment-card"><div><StatusBadge status={item.status}/><h3>{item.department?.name}</h3><strong>{item.appointmentNumber}</strong><p>{item.hospital?.name}</p><p>Dr. {item.doctor?.firstName} {item.doctor?.lastName} - {fmt(item.appointmentDate)} - {clock(item.startTime)}</p></div><div className="card-actions"><button onClick={()=>setSelected(item)}>View Details</button>{['PENDING','CONFIRMED'].includes(item.status)&&<><button onClick={()=>reschedule(item)}>Reschedule</button><button className="danger" onClick={()=>cancel(item)}>Cancel</button></>}</div></article>)}</div>{!visible.length&&<p>No appointments in this category.</p>}{selected&&<div className="patient-detail" role="dialog" aria-modal="true"><button className="close" aria-label="Close details" onClick={()=>setSelected(null)}>X</button><h3>{selected.appointmentNumber}</h3><StatusBadge status={selected.status}/><p><b>Hospital:</b> {selected.hospital?.name}</p><p><b>Department:</b> {selected.department?.name}</p><p><b>Doctor:</b> Dr. {selected.doctor?.firstName} {selected.doctor?.lastName}</p><p><b>Date:</b> {fmt(selected.appointmentDate)} at {clock(selected.startTime)}</p><p><b>Reason:</b> {selected.reasonForVisit}</p><p><b>Booking method:</b> {selected.bookingMethod.replaceAll('_',' ')}</p></div>}</section>;
}
