import { useEffect, useMemo, useState } from 'react';
import { appointmentService } from '../../services/appointmentService';
import { patientCardService } from '../../services/patientCardService';
import { patientService } from '../../services/patientService';

const STEPS = ['Hospital', 'Department', 'Date', 'Doctor & Time', 'Card', 'Details', 'Confirm'];
const DAY_INDEX = { SUNDAY: 0, MONDAY: 1, TUESDAY: 2, WEDNESDAY: 3, THURSDAY: 4, FRIDAY: 5, SATURDAY: 6 };
const time = (value) => new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', timeZone: 'UTC' });

export default function BookAppointmentPage({ onBooked, openCards, initialSelection }) {
  const [step, setStep] = useState(0); const [data, setData] = useState({ reasonForVisit: '', symptomsSummary: '', hospitalId: initialSelection?.hospitalId || '', departmentId: initialSelection?.departmentId || '', symptomAssessmentId: initialSelection?.assessmentId || null });
  const [hospitals, setHospitals] = useState([]); const [departments, setDepartments] = useState([]); const [doctors, setDoctors] = useState([]); const [cards, setCards] = useState([]);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [confirmed, setConfirmed] = useState(null);
  const today = new Date().toISOString().slice(0, 10); const maxDate = new Date(Date.now() + 60 * 86400000).toISOString().slice(0, 10);
  useEffect(() => { patientService.hospitals().then(r => setHospitals(r.data)).catch(e => setError(e.message)); patientCardService.list().then(r => setCards(r.data)).catch(() => {}); }, []);
  useEffect(() => { if (data.hospitalId) patientService.departments(data.hospitalId).then(r => setDepartments(r.data)).catch(e => setError(e.message)); }, [data.hospitalId]);
  useEffect(() => { if (data.departmentId && data.date) patientService.doctors(data.departmentId, data.date).then(r => setDoctors(r.data)).catch(e => setError(e.message)); }, [data.departmentId, data.date]);
  const hospital = hospitals.find(x => x.id === data.hospitalId); const department = departments.find(x => x.id === data.departmentId); const slot = doctors.flatMap(x => x.appointmentSlots.map(s => ({ ...s, doctor: x }))).find(x => x.id === data.slotId); const card = cards.find(x => x.id === data.patientCardId);
  const validDays = useMemo(() => new Set((department?.schedules || []).map(s => DAY_INDEX[s.dayOfWeek])), [department]);
  const canContinue = [data.hospitalId, data.departmentId, data.date && validDays.has(new Date(`${data.date}T12:00:00`).getDay()), data.slotId, data.patientCardId, data.reasonForVisit.trim().length >= 3, true][step];
  const choose = (values) => { setData(old => ({ ...old, ...values })); setError(''); };
  const recommend = async () => { setBusy(true); try { const r = await patientService.recommendation(data.hospitalId, data.departmentId, data.date); choose({ slotId: r.data.recommendedSlot.id }); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const confirm = async () => { if (!navigator.onLine) return setError('Booking requires an internet connection. Nothing was submitted.'); setBusy(true); try { const r = await appointmentService.book({ slotId: data.slotId, patientCardId: data.patientCardId, symptomAssessmentId: data.symptomAssessmentId || null, reasonForVisit: data.reasonForVisit, symptomsSummary: data.symptomsSummary || null }); setConfirmed(r.data); onBooked?.(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  if (confirmed) return <section className="patient-panel booking-confirmed"><h2>Appointment Confirmed</h2><strong>{confirmed.appointmentNumber}</strong><p>{confirmed.hospital?.name} · {confirmed.department?.name}</p><p>Dr. {confirmed.doctor?.firstName} {confirmed.doctor?.lastName}</p><p>{new Date(confirmed.appointmentDate).toLocaleDateString()} at {time(confirmed.startTime)}</p><button onClick={() => onBooked?.('appointments')}>Go to My Appointments</button></section>;
  return <section className="patient-panel booking-page"><h2>Book an appointment</h2><ol className="booking-steps">{STEPS.map((label, index) => <li key={label} className={index === step ? 'active' : index < step ? 'done' : ''}><span>{index + 1}</span>{label}</li>)}</ol>{error && <p className="patient-error" role="alert">{error}</p>}
    {step === 0 && <div className="choice-grid">{hospitals.map(x => <button key={x.id} className={data.hospitalId === x.id ? 'selected' : ''} onClick={() => choose({ hospitalId: x.id, departmentId: '', date: '', slotId: '', patientCardId: '' })}><strong>{x.name}</strong><small>{x.city}, {x.region}</small></button>)}</div>}
    {step === 1 && <div className="choice-grid">{departments.map(x => <button key={x.id} className={data.departmentId === x.id ? 'selected' : ''} onClick={() => choose({ departmentId: x.id, date: '', slotId: '' })}><strong>{x.name}</strong><small>{x.description}</small><small>{x.schedules.map(s => `${s.dayOfWeek} ${time(s.startTime)}–${time(s.endTime)}`).join(' · ') || 'No clinic days configured'}</small></button>)}</div>}
    {step === 2 && <div><label htmlFor="appointment-date">Eligible clinic date</label><input id="appointment-date" type="date" min={today} max={maxDate} value={data.date || ''} onChange={e => choose({ date: e.target.value, slotId: '' })}/>{data.date && !canContinue && <p className="patient-error">This department does not operate on the selected day.</p>}<p className="patient-help">Booking dates are available up to 60 days ahead.</p></div>}
    {step === 3 && <div><button disabled={busy} onClick={recommend}>Recommend earliest available doctor</button><div className="slot-list">{doctors.flatMap(doctor => doctor.appointmentSlots.map(s => <button key={s.id} className={data.slotId === s.id ? 'selected' : ''} onClick={() => choose({ slotId: s.id })}><strong>Dr. {doctor.firstName} {doctor.lastName}</strong><span>{time(s.startTime)}–{time(s.endTime)}</span><small>{doctor.specialization} · {s.capacity - s.bookedCount} place(s)</small></button>))}</div>{!doctors.length && <p>No appointments are available for this date. Please choose another clinic day.</p>}</div>}
    {step === 4 && <div className="choice-grid">{cards.filter(x => x.hospitalId === data.hospitalId).map(x => <button key={x.id} disabled={x.verificationStatus !== 'VERIFIED'} className={data.patientCardId === x.id ? 'selected' : ''} onClick={() => choose({ patientCardId: x.id })}><strong>{x.cardType.replace('_', ' ')}</strong><span>{x.cardNumber}</span><small>{x.verificationStatus === 'PENDING' ? 'Pending hospital verification' : x.verificationStatus}</small></button>)}</div>}{step === 4 && !cards.some(x => x.hospitalId === data.hospitalId && x.verificationStatus === 'VERIFIED') && <p>No verified card is available. <button onClick={openCards}>Add Hospital/NHIS Card</button></p>}
    {step === 5 && <div className="form-stack"><label>Reason for visit<textarea value={data.reasonForVisit} maxLength={1000} onChange={e => choose({ reasonForVisit: e.target.value })} required/></label><label>Brief symptoms or complaint (optional)<textarea value={data.symptomsSummary} maxLength={2000} onChange={e => choose({ symptomsSummary: e.target.value })}/></label><p className="patient-help">This does not provide a diagnosis. Symptom assessment is planned for Phase 7.</p></div>}
    {step === 6 && <div className="booking-summary"><h3>Booking summary</h3><p><b>Hospital:</b> {hospital?.name}</p><p><b>Department:</b> {department?.name}</p><p><b>Doctor:</b> Dr. {slot?.doctor.firstName} {slot?.doctor.lastName}</p><p><b>Date/time:</b> {data.date} · {slot && time(slot.startTime)}</p><p><b>Card:</b> {card?.cardType.replace('_', ' ')} {card?.cardNumber}</p><p><b>Reason:</b> {data.reasonForVisit}</p></div>}
    <div className="wizard-actions">{step > 0 && <button className="secondary" disabled={busy} onClick={() => setStep(step - 1)}>Back</button>}{step < 6 ? <button disabled={!canContinue || busy} onClick={() => setStep(step + 1)}>Continue</button> : <button disabled={busy} onClick={confirm}>{busy ? 'Booking…' : 'Confirm Booking'}</button>}</div>
  </section>;
}
