import { useEffect, useState } from 'react';
import { patientCardService } from '../../services/patientCardService';
import { patientService } from '../../services/patientService';
import StatusBadge from '../../components/patient/StatusBadge';
export default function PatientCardsPage() {
 const [cards,setCards]=useState([]),[hospitals,setHospitals]=useState([]),[error,setError]=useState(''),[form,setForm]=useState({hospitalId:'',cardType:'HOSPITAL_CARD',cardNumber:'',expiresAt:''});
 const load=()=>patientCardService.list().then(r=>setCards(r.data)).catch(e=>setError(e.message)); useEffect(()=>{load();patientService.hospitals().then(r=>setHospitals(r.data));},[]);
 const submit=async e=>{e.preventDefault();if(!navigator.onLine)return setError('Card submission requires an internet connection. Nothing was submitted.');try{await patientCardService.create({...form,expiresAt:form.expiresAt||null});setForm({...form,cardNumber:'',expiresAt:''});load();}catch(x){setError(x.message)}};
 return <section className="patient-panel"><h2>My cards</h2><p>Cards are verified manually by the selected hospital. This is not an official NHIA/NHIS database verification.</p>{error&&<p className="patient-error">{error}</p>}<div className="card-grid">{cards.map(x=><article key={x.id} className="health-card"><StatusBadge status={x.verificationStatus}/><h3>{x.cardType.replace('_',' ')}</h3><strong>{x.cardNumber}</strong><p>{x.hospital?.name||hospitals.find(h=>h.id===x.hospitalId)?.name}</p>{x.rejectionReason&&<p>Reason: {x.rejectionReason}</p>}</article>)}</div><form className="patient-form" onSubmit={submit}><h3>Link a card</h3><label>Hospital<select required value={form.hospitalId} onChange={e=>setForm({...form,hospitalId:e.target.value})}><option value="">Select hospital</option>{hospitals.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Card type<select value={form.cardType} onChange={e=>setForm({...form,cardType:e.target.value})}><option value="HOSPITAL_CARD">Hospital Card</option><option value="NHIS_CARD">NHIS Card</option></select></label><label>Card number<input required minLength="4" maxLength="80" autoComplete="off" value={form.cardNumber} onChange={e=>setForm({...form,cardNumber:e.target.value})}/></label><label>Expiry date (optional)<input type="date" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label><button>Submit for verification</button></form></section>;
}
