import prisma from '../config/prisma.js';
import { getPatientProfileId } from '../services/authorizationService.js';
import { appointmentService } from '../services/appointmentService.js';
import { appointmentRecommendationService } from '../services/appointmentRecommendationService.js';
import { patientCardService } from '../services/patientCardService.js';
import { patientService } from '../services/patientService.js';
import { notificationService } from '../services/notificationService.js';
import { auditService } from '../services/auditService.js';
import { careSyncHospitalService } from '../services/careSyncHospitalService.js';

export const patientSelfServiceController = {
  async hospitals(_request, response) { response.json({ success: true, data: [await careSyncHospitalService.get()] }); },
  async careSyncDepartments(_request, response) { const hospital = await careSyncHospitalService.get(); const data = await prisma.department.findMany({ where: { hospitalId: hospital.id, active: true }, select: { id: true, hospitalId: true, name: true, code: true, description: true, requiresAppointment: true, schedules: { where: { active: true }, select: { id: true, dayOfWeek: true, startTime: true, endTime: true, dailyCapacity: true }, orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }] } }, orderBy: { name: 'asc' } }); response.json({ success: true, data, hospital }); },
  async departments(request, response) { const data = await prisma.department.findMany({ where: { hospitalId: request.params.hospitalId, active: true }, select: { id: true, hospitalId: true, name: true, code: true, description: true, requiresAppointment: true, schedules: { where: { active: true }, select: { id: true, dayOfWeek: true, startTime: true, endTime: true, dailyCapacity: true }, orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }] } }, orderBy: { name: 'asc' } }); response.json({ success: true, data }); },
  async availability(request, response) { const department = await prisma.department.findUnique({ where: { id: request.params.departmentId }, select: { id: true, hospitalId: true, name: true, active: true, schedules: { where: { active: true }, orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }] } } }); response.json({ success: true, data: department }); },
  async doctors(request, response) { const date = request.validatedQuery?.date ? new Date(`${request.validatedQuery.date}T00:00:00.000Z`) : null; const data = await prisma.doctorProfile.findMany({ where: { active: true, departments: { some: { departmentId: request.params.departmentId, active: true } }, ...(date ? { appointmentSlots: { some: { departmentId: request.params.departmentId, date, status: 'AVAILABLE' } } } : {}) }, select: { id: true, firstName: true, lastName: true, specialization: true, qualification: true, appointmentSlots: { where: { departmentId: request.params.departmentId, ...(date ? { date } : {}), status: 'AVAILABLE' }, select: { id: true, date: true, startTime: true, endTime: true, capacity: true, bookedCount: true }, orderBy: { startTime: 'asc' } } }, orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }] }); response.json({ success: true, data: data.map((doctor) => ({ ...doctor, appointmentSlots: doctor.appointmentSlots.filter((slot) => slot.bookedCount < slot.capacity) })) }); },
  async recommend(request, response) { const hospital = await careSyncHospitalService.get(); response.json({ success: true, data: await appointmentRecommendationService.recommend({ ...request.validatedQuery, hospitalId: hospital.id }) }); },
  async book(request, response) { const data = await appointmentService.createPatientBooking({ patientId: getPatientProfileId(request.auth), userId: request.auth.userId, ...request.body, request }); response.status(201).json({ success: true, data }); },
  async appointments(request, response) { response.json({ success: true, data: await appointmentService.list({ patientId: getPatientProfileId(request.auth) }) }); },
  async appointment(request, response) { const item = await appointmentService.get(request.params.id); if (item.patientId !== getPatientProfileId(request.auth)) return response.status(403).json({ success: false, message: 'Not authorized' }); response.json({ success: true, data: item }); },
  async cancel(request, response) { response.json({ success: true, data: await appointmentService.cancelPatientAppointment(request.params.id, getPatientProfileId(request.auth), request.auth.userId, request.body.cancellationReason, request) }); },
  async reschedule(request, response) { response.json({ success: true, data: await appointmentService.reschedulePatientAppointment(request.params.id, getPatientProfileId(request.auth), request.auth.userId, request.body.newSlotId, request) }); },
  async cards(request, response) { response.json({ success: true, data: await patientCardService.list(getPatientProfileId(request.auth)) }); },
  async createCard(request, response) { const hospital = await careSyncHospitalService.get(); const card = await patientCardService.create(getPatientProfileId(request.auth), { ...request.body, hospitalId: hospital.id }); await notificationService.create({ userId: request.auth.userId, hospitalId: card.hospitalId, title: 'Card submitted', message: 'Your card is pending manual CareSync verification.', type: 'CARD_VERIFICATION' }); await auditService.record({ userId: request.auth.userId, hospitalId: card.hospitalId, action: 'PATIENT_CARD_SUBMITTED', resourceType: 'PatientCard', resourceId: card.id, request }); response.status(201).json({ success: true, data: card }); },
  async profile(request, response) { response.json({ success: true, data: await patientService.get(getPatientProfileId(request.auth)) }); },
  async updateProfile(request, response) { const data = await patientService.update(getPatientProfileId(request.auth), request.body); await auditService.record({ userId: request.auth.userId, action: 'PATIENT_PROFILE_UPDATED', resourceType: 'PatientProfile', resourceId: data.id, request }); response.json({ success: true, data }); },
  async notifications(request, response) { response.json({ success: true, data: await notificationService.list(request.auth.userId) }); },
  async readNotification(request, response) { response.json({ success: true, data: await notificationService.markRead(request.params.id, request.auth.userId) }); },
  async readAllNotifications(request, response) { response.json({ success: true, data: await notificationService.markAllRead(request.auth.userId) }); },
};
