import { useEffect, useState } from 'react';
import { adminReviewService } from '../../services/adminReviewService';
import { departmentService } from '../../services/departmentService';
import { doctorService } from '../../services/doctorService';
const download=(name,rows)=>{if(!rows.length)return;const keys=Object.keys(rows[0]),csv=[keys.join(','),...rows.map(row=>keys.map(key=>`"${String(row[key]??'').replaceAll('"','""')}"`).join(','))].join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)};
const parseCsv=text=>{const[header,...lines]=text.trim().split(/\r?\n/),keys=header.split(',').map(x=>x.trim());return lines.filter(Boolean).map(line=>Object.fromEntries(line.split(',').map((value,index)=>[keys[index],value.trim()]))) };
export default function ReviewAdminPanel({section}){
 const[data,setData]=useState(null),[nurses,setNurses]=useState([]),[departments,setDepartments]=useState([]),[doctors,setDoctors]=useState([]),[filters,setFilters]=useState({}),[message,setMessage]=useState('');
 const load=async()=>{try{const[n,d,docs]=await Promise.all([adminReviewService.nurses(),departmentService.listManaged(),doctorService.listManaged()]);setNurses(n.data);setDepartments(d.data);setDoctors(docs.data);if(section==='analytics')setData((await adminReviewService.analytics()).data);if(['appointments','reports'].includes(section))setData((await adminReviewService[section](filters)).data)}catch(error){setMessage(error.message)}};useEffect(()=>{load()},[section]);
 if(section==='analytics')return <section className="glass-panel" style={{padding:'2rem'}}><h2>CareSync Analytics</h2>{message&&<p>{message}</p>}{data&&<><div className="grid-4">{Object.entries(data).filter(([,value])=>typeof value==='number').map(([key,value])=><article key={key}><small>{key.replace(/([A-Z])/g,' $1')}</small><h3>{value}</h3></article>)}</div><h3>Appointments by department</h3>{data.appointmentsByDepartment?.map(item=><p key={item.id}>{item.name}: {item.count}</p>)}</>}</section>;
 if(section==='staff')return <section className="glass-panel" style={{padding:'2rem'}}><h2>Medical Staff Directory</h2><h3>Doctors</h3>{doctors.map(doctor=><article key={doctor.id}><b>Dr. {doctor.firstName} {doctor.lastName}</b> · {doctor.specialization} · {doctor.active?'Active':'Inactive'}<p>{doctor.departments?.filter(x=>x.active).map(x=>x.department.name).join(', ')||'No department'}</p></article>)}<h3>Nurses</h3>{nurses.map(nurse=><article key={nurse.id}><b>{nurse.firstName} {nurse.lastName}</b> · {nurse.employeeNumber} · {nurse.active?'Active':'Inactive'}<p>{nurse.departments?.filter(x=>x.active).map(x=>x.department.name).join(', ')||'No department'}</p><select defaultValue="" onChange={async event=>{if(event.target.value){await adminReviewService.assignNurseDepartment(nurse.id,event.target.value);setMessage('Nurse assigned.');load()}}}><option value="">Assign department</option>{departments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></article>)}</section>;
 if(section==='bulk')return <Bulk data={data} setData={setData} message={message} setMessage={setMessage}/>;
 const rows=Array.isArray(data)?data:[];
 return <section className="glass-panel" style={{padding:'2rem'}}><h2>{section==='reports'?'Administrative Reports':'Appointment Monitoring'}</h2><div className="management-form-grid"><input type="date" onChange={e=>setFilters({...filters,from:e.target.value})}/><input type="date" onChange={e=>setFilters({...filters,to:e.target.value})}/><select onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{['PENDING','CONFIRMED','CHECKED_IN','TRIAGED','WAITING','IN_CONSULTATION','COMPLETED','CANCELLED','MISSED'].map(x=><option key={x}>{x}</option>)}</select><select onChange={e=>setFilters({...filters,departmentId:e.target.value})}><option value="">All departments</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button onClick={async()=>setData((await adminReviewService[section](filters)).data)}>Apply filters</button><button onClick={()=>download(`caresync-${section}.csv`,rows.map(item=>({appointmentNumber:item.appointmentNumber,patient:`${item.patient.firstName} ${item.patient.lastName}`,department:item.department.name,doctor:`${item.doctor.firstName} ${item.doctor.lastName}`,date:new Date(item.appointmentDate).toISOString().slice(0,10),status:item.status})))}>Export CSV</button></div>{rows.map(item=><article key={item.id}><b>{item.appointmentNumber}</b> · {item.patient.firstName} {item.patient.lastName} · {item.department.name} · {item.status}<select defaultValue="" onChange={async e=>{if(e.target.value){await adminReviewService.assignNurseAppointment(item.id,e.target.value);setMessage('Nurse assigned to appointment.');load()}}}><option value="">Assign nurse</option>{nurses.map(n=><option key={n.id} value={n.id}>{n.firstName} {n.lastName}</option>)}</select></article>)}</section>;
}
function Bulk({data,setData,message,setMessage}){const change=async event=>{try{const rows=parseCsv(await event.target.files[0].text()),result=(await adminReviewService.bulkImport(rows)).data;setData(result);setMessage(`Processed ${result.total}: ${result.successful} successful, ${result.failed} failed.`)}catch(error){setMessage(error.details?.map(x=>x.message).join('. ')||error.message)}};return <section className="glass-panel" style={{padding:'2rem'}}><h2>Secure Bulk Staff Import</h2><p>Only DOCTOR and NURSE are accepted. Files are parsed in memory and not retained.</p><button onClick={()=>download('caresync-staff-template.csv',[{firstName:'',lastName:'',email:'',phone:'',employeeNumber:'',role:'DOCTOR',department:'General OPD',specialization:'',qualification:'',licenseNumber:'',initialPassword:''}])}>Download CSV template</button><input type="file" accept=".csv,text/csv" onChange={change}/>{message&&<p>{message}</p>}{data?.rows?.map((row,index)=><p key={index}>{row.name} · {row.email} · {row.status}{row.error?` — ${row.error}`:''}</p>)}</section>}
