import{normalizeSymptoms}from'./symptomNormalizer.js';import{screenRedFlags}from'./redFlagService.js';import{assessSymptoms}from'./symptomAssessmentAdapter.js';import{resolveDepartment}from'./departmentRecommendationService.js';import{assessUrgency,actionFor}from'./urgencyAssessmentService.js';import{aiModelService}from'../services/aiModelService.js';import{env}from'../config/env.js';
const DISPLAY={viral_respiratory_illness:'Viral respiratory illness',ent_concern:'Ear, nose or throat concern',gastrointestinal_illness:'Gastrointestinal illness',urinary_tract_concern:'Urinary tract concern',allergy_related_condition:'Allergy-related condition',asthma_like_respiratory_concern:'Asthma-like respiratory concern',eye_related_condition:'Eye-related condition'};
const strength=(score,threshold)=>score>=Math.max(.7,threshold)?'HIGHER_MATCH':score>=threshold?'MODERATE_MATCH':'LOWER_MATCH';
export async function assessSymptomsHybrid(input,dependencies={}){
  const normalizedSymptoms=normalizeSymptoms(input.symptomsText,input.symptoms);if(input.temperature>=38&&!normalizedSymptoms.includes('fever'))normalizedSymptoms.push('fever');
  const redFlags=screenRedFlags(normalizedSymptoms,input);if(redFlags.length)return assessSymptoms({...input,symptoms:normalizedSymptoms});
  if(env.NODE_ENV==='test'&&!dependencies.modelService)return assessSymptoms({...input,symptoms:normalizedSymptoms});
  try{
    const prediction=await(dependencies.modelService||aiModelService).predict({symptoms:Object.fromEntries(normalizedSymptoms.map(item=>[item,true])),severity:input.severity,durationDays:input.durationDays??null,temperature:input.temperature??null,heartRate:input.heartRate??null,oxygenSaturation:input.oxygenSaturation??null});
    const category=prediction.lowConfidence?'GENERAL':prediction.predictions[0].departmentCategory,recommendedDepartment=await resolveDepartment(input.hospitalId,category),urgency=assessUrgency({redFlags:[],severity:input.severity,symptoms:normalizedSymptoms});
    return{possibleConditions:prediction.predictions.map(item=>({displayName:DISPLAY[item.condition]||item.condition.replaceAll('_',' '),matchStrength:strength(item.score,prediction.confidenceThreshold),matchedSymptoms:normalizedSymptoms,shortReason:'The trained model ranked this category using the reported symptom pattern.'})),recommendedDepartment,recommendedDepartmentCategory:category,urgency,recommendedAction:actionFor(urgency,recommendedDepartment),explanation:prediction.lowConfidence?'Your symptoms are not specific enough for a reliable preliminary match. General clinical assessment is recommended.':`The model found a preliminary symptom-pattern match. ${recommendedDepartment?`${recommendedDepartment.name} is suggested for professional assessment.`:'Contact the hospital for appropriate routing.'}`,redFlags:[],normalizedSymptoms,assessmentMethod:'ML_HYBRID',modelVersion:prediction.modelVersion,disclaimer:'This is an AI-assisted preliminary assessment, not a confirmed diagnosis. Dataset performance is not Ghanaian clinical validation, and a healthcare professional must assess your symptoms.'};
  }catch{const fallback=await assessSymptoms({...input,symptoms:normalizedSymptoms});return{...fallback,assessmentMethod:'RULE_BASED_FALLBACK'};}
}
