import prisma from '../config/prisma.js'; import { AppError } from '../middleware/errorHandler.js'; import { auditService } from './auditService.js'; import { notificationService } from './notificationService.js';
const contextInclude={patient:{select:{id:true,userId:true,firstName:true,lastName:true,dateOfBirth:true}},department:{select:{id:true,name:true}},hospital:{select:{id:true,name:true}},triageRecords:{orderBy:{createdAt:'desc'},take:1},vitalRecords:{orderBy:{recordedAt:'desc'}},consultation:true};
async function assigned(id,doctorId,client=prisma){const item=await client.appointment.findUnique({where:{id},include:contextInclude});if(!item)throw new AppError('Appointment not found',404);if(item.doctorId!==doctorId)throw new AppError('Doctor is not assigned to this appointment',403);return item;}
export const consultationService={
 getContext:(id,doctorId)=>assigned(id,doctorId),
 async start(id,doctor,request){return prisma.$transaction(async tx=>{const appointment=await assigned(id,doctor.id,tx);if(appointment.status!=='WAITING')throw new AppError('Only a waiting appointment can start consultation',409);const now=new Date();const changed=await tx.appointment.updateMany({where:{id,status:'WAITING'},data:{status:'IN_CONSULTATION',consultationStartedAt:now}});if(changed.count!==1)throw new AppError('Consultation was started concurrently',409);const chief=appointment.triageRecords[0]?.chiefComplaint||appointment.reasonForVisit;const consultation=await tx.consultation.upsert({where:{appointmentId:id},update:{},create:{appointmentId:id,patientId:appointment.patientId,doctorId:doctor.id,hospitalId:appointment.hospitalId,chiefComplaint:chief,startedAt:now}});await auditService.record({userId:doctor.userId,hospitalId:appointment.hospitalId,action:'CONSULTATION_STARTED',resourceType:'Consultation',resourceId:consultation.id,metadata:{appointmentId:id},request},tx);return consultation;},{isolationLevel:'Serializable'});},
 async save(id,doctor,data,request){const appointment=await assigned(id,doctor.id);if(appointment.status!=='IN_CONSULTATION')throw new AppError('Consultation is not active',409);const consultation=await prisma.consultation.update({where:{appointmentId:id},data:{...data,followUpDate:data.followUpDate?new Date(`${data.followUpDate}T00:00:00.000Z`):null}});await auditService.record({userId:doctor.userId,hospitalId:appointment.hospitalId,action:'CONSULTATION_UPDATED',resourceType:'Consultation',resourceId:consultation.id,metadata:{appointmentId:id,followUpRequired:data.followUpRequired},request});return consultation;},
 async complete(id,doctor,data,request){return prisma.$transaction(async tx=>{const appointment=await assigned(id,doctor.id,tx);if(appointment.status!=='IN_CONSULTATION')throw new AppError('Consultation is not active',409);const now=new Date();const consultation=await tx.consultation.update({where:{appointmentId:id},data:{...data,followUpDate:data.followUpDate?new Date(`${data.followUpDate}T00:00:00.000Z`):null,completedAt:now}});const changed=await tx.appointment.updateMany({where:{id,status:'IN_CONSULTATION'},data:{status:'COMPLETED',completedAt:now}});if(changed.count!==1)throw new AppError('Consultation completion conflicted with another request',409);await notificationService.create({userId:appointment.patient.userId,hospitalId:appointment.hospitalId,title:'Consultation completed',message:data.followUpRequired?'Your consultation is complete. Follow-up was recommended.':'Your consultation is complete.',type:'CONSULTATION'},tx);await auditService.record({userId:doctor.userId,hospitalId:appointment.hospitalId,action:'CONSULTATION_COMPLETED',resourceType:'Consultation',resourceId:consultation.id,metadata:{appointmentId:id,followUpRequired:data.followUpRequired},request},tx);if(data.followUpRequired)await auditService.record({userId:doctor.userId,hospitalId:appointment.hospitalId,action:'FOLLOW_UP_RECOMMENDED',resourceType:'Consultation',resourceId:consultation.id,metadata:{appointmentId:id,followUpDate:data.followUpDate||null},request},tx);return consultation;},{isolationLevel:'Serializable'});},
 async patientSummary(appointmentId,patientId){const item=await prisma.consultation.findUnique({where:{appointmentId},include:{doctor:{select:{firstName:true,lastName:true,specialization:true}},appointment:{select:{appointmentDate:true,patientId:true,status:true}}}});if(!item)throw new AppError('Consultation not found',404);if(item.patientId!==patientId)throw new AppError('Not authorized',403);if(!item.completedAt)throw new AppError('Consultation summary is not yet available',409);return{id:item.id,appointmentId,doctor:item.doctor,date:item.appointment.appointmentDate,diagnosis:item.diagnosis,treatmentPlan:item.treatmentPlan,followUpRequired:item.followUpRequired,followUpDate:item.followUpDate,completedAt:item.completedAt};}
};
