import prisma from '../config/prisma.js';
import { AppError } from '../middleware/errorHandler.js';
import { getAdminHospitalId } from './authorizationService.js';
import { staffAccountService } from './staffAccountService.js';
import { auditService } from './auditService.js';

const dayStart = (value) => value ? new Date(`${value}T00:00:00.000Z`) : undefined;
const dayEnd = (value) => value ? new Date(`${value}T23:59:59.999Z`) : undefined;
const appointmentInclude = { patient: { select: { id:true,firstName:true,lastName:true } }, department:{select:{id:true,name:true}}, doctor:{select:{id:true,firstName:true,lastName:true}}, nurseAssignments:{where:{active:true},include:{nurse:{select:{id:true,firstName:true,lastName:true}}}}, triageRecords:{take:1,orderBy:{createdAt:'desc'}}, vitalRecords:{where:{verificationStatus:'VERIFIED'},take:1,orderBy:{recordedAt:'desc'}} };

function appointmentWhere(hospitalId, query={}) { return { hospitalId, ...(query.departmentId?{departmentId:query.departmentId}:{}), ...(query.doctorId?{doctorId:query.doctorId}:{}), ...(query.status?{status:query.status}:{}), ...(query.nurseId?{nurseAssignments:{some:{nurseId:query.nurseId,active:true}}}:{}), ...((query.from||query.to)?{appointmentDate:{...(query.from?{gte:dayStart(query.from)}:{}),...(query.to?{lte:dayEnd(query.to)}:{})}}:{}) }; }

export const reviewCorrectionService = {
  nurses(auth) { const hospitalId=getAdminHospitalId(auth); return prisma.nurseProfile.findMany({where:{hospitalId},include:{user:{select:{email:true,active:true}},departments:{include:{department:{select:{id:true,name:true}}}}},orderBy:{lastName:'asc'}}); },
  async assignNurseDepartment(auth,nurseId,{departmentId,active},request){const hospitalId=getAdminHospitalId(auth);const [nurse,department]=await Promise.all([prisma.nurseProfile.findFirst({where:{id:nurseId,hospitalId}}),prisma.department.findFirst({where:{id:departmentId,hospitalId}})]);if(!nurse||!department)throw new AppError('Nurse or department not found in CareSync',404);const item=await prisma.nurseDepartment.upsert({where:{nurseId_departmentId:{nurseId,departmentId}},update:{active},create:{nurseId,departmentId,active},include:{department:true}});await auditService.record({userId:auth.userId,hospitalId,action:'NURSE_DEPARTMENT_ASSIGNED',resourceType:'NurseDepartment',resourceId:item.id,metadata:{nurseId,departmentId,active},request});return item;},
  async assignNurseAppointment(auth,appointmentId,{nurseId,active},request){const hospitalId=getAdminHospitalId(auth);const [nurse,appointment]=await Promise.all([prisma.nurseProfile.findFirst({where:{id:nurseId,hospitalId}}),prisma.appointment.findFirst({where:{id:appointmentId,hospitalId}})]);if(!nurse||!appointment)throw new AppError('Nurse or appointment not found in CareSync',404);const department=await prisma.nurseDepartment.findUnique({where:{nurseId_departmentId:{nurseId,departmentId:appointment.departmentId}}});if(!department?.active)throw new AppError('Nurse is not assigned to the appointment department',409);const item=await prisma.nurseAppointmentAssignment.upsert({where:{nurseId_appointmentId:{nurseId,appointmentId}},update:{active,unassignedAt:active?null:new Date(),assignedByUserId:auth.userId},create:{nurseId,appointmentId,assignedByUserId:auth.userId,active},include:{nurse:true}});await auditService.record({userId:auth.userId,hospitalId,action:active?'NURSE_ASSIGNED_TO_APPOINTMENT':'NURSE_UNASSIGNED_FROM_APPOINTMENT',resourceType:'NurseAppointmentAssignment',resourceId:item.id,metadata:{nurseId,appointmentId},request});return item;},
  appointments(auth,query){return prisma.appointment.findMany({where:appointmentWhere(getAdminHospitalId(auth),query),include:appointmentInclude,orderBy:[{appointmentDate:'desc'},{startTime:'asc'}]});},
  async analytics(auth){const hospitalId=getAdminHospitalId(auth),now=new Date(),today=new Date(now);today.setHours(0,0,0,0);const week=new Date(today);week.setDate(week.getDate()-6);const month=new Date(today.getFullYear(),today.getMonth(),1);const [patients,doctors,nurses,appointments,departments]=await Promise.all([prisma.patientProfile.count(),prisma.doctorHospital.count({where:{hospitalId,active:true}}),prisma.nurseProfile.count({where:{hospitalId,active:true}}),prisma.appointment.findMany({where:{hospitalId},select:{patientId:true,appointmentDate:true,status:true,departmentId:true,doctorId:true,nurseAssignments:{where:{active:true},select:{nurseId:true}}}}),prisma.department.findMany({where:{hospitalId},select:{id:true,name:true}})]);const uniqueSince=(date)=>new Set(appointments.filter(a=>a.appointmentDate>=date).map(a=>a.patientId)).size;const countSince=(date)=>appointments.filter(a=>a.appointmentDate>=date).length;const group=(key)=>Object.entries(appointments.reduce((map,a)=>{const id=a[key];map[id]=(map[id]||0)+1;return map},{})).map(([id,count])=>({id,count}));return{totalPatients:patients,uniquePatientsToday:uniqueSince(today),uniquePatientsWeek:uniqueSince(week),uniquePatientsMonth:uniqueSince(month),appointmentsToday:countSince(today),appointmentsWeek:countSince(week),appointmentsMonth:countSince(month),completed:appointments.filter(a=>a.status==='COMPLETED').length,pendingConfirmed:appointments.filter(a=>['PENDING','CONFIRMED'].includes(a.status)).length,cancelled:appointments.filter(a=>a.status==='CANCELLED').length,doctors,nurses,appointmentsByDepartment:group('departmentId').map(x=>({...x,name:departments.find(d=>d.id===x.id)?.name||'Unknown'})),doctorWorkload:group('doctorId'),nurseWorkload:Object.entries(appointments.flatMap(a=>a.nurseAssignments.map(n=>n.nurseId)).reduce((m,id)=>{m[id]=(m[id]||0)+1;return m},{})).map(([id,count])=>({id,count}))};},
  async bulkImport(auth,rows,request){const hospitalId=getAdminHospitalId(auth),results=[];for(const row of rows){try{const department=await prisma.department.findFirst({where:{hospitalId,active:true,name:{equals:row.department,mode:'insensitive'}}});if(!department)throw new AppError('Unknown or inactive department',400);if(row.role==='DOCTOR')await staffAccountService.createDoctor(auth,{firstName:row.firstName,lastName:row.lastName,email:row.email,password:row.initialPassword,phone:row.phone,employeeNumber:row.employeeNumber,licenseNumber:row.licenseNumber,specialization:row.specialization||'General Practice',qualification:row.qualification||'Not provided',startedAt:new Date().toISOString().slice(0,10),departmentId:department.id,primaryDepartment:true},request);else{const created=await staffAccountService.createNurse(auth,{firstName:row.firstName,lastName:row.lastName,email:row.email,password:row.initialPassword,phone:row.phone,employeeNumber:row.employeeNumber,licenseNumber:row.licenseNumber},request);await reviewCorrectionService.assignNurseDepartment(auth,created.profile.id,{departmentId:department.id,active:true},request);}results.push({name:`${row.firstName} ${row.lastName}`,email:row.email,role:row.role,department:row.department,status:'SUCCESS'});}catch(error){results.push({name:`${row.firstName} ${row.lastName}`,email:row.email,role:row.role,department:row.department,status:'FAILED',error:error.message});}}return{total:rows.length,successful:results.filter(x=>x.status==='SUCCESS').length,failed:results.filter(x=>x.status==='FAILED').length,rows:results};},
};
