import { afterAll, beforeAll, describe, expect, test } from 'vitest';
import { randomUUID } from 'node:crypto';
import prisma from '../src/config/prisma.js';
import { appointmentService } from '../src/services/appointmentService.js';
import { appointmentRecommendationService } from '../src/services/appointmentRecommendationService.js';
import { maskCardNumber } from '../src/utils/card.js';
import { availabilitySchema } from '../src/validators/patientSelfServiceValidators.js';

const tag = randomUUID().slice(0, 8); const userIds = []; let hospital; let department; let doctor; let slot; let secondSlot; let patients = []; let cards = [];
const future = new Date(); future.setUTCDate(future.getUTCDate() + 14); future.setUTCHours(0,0,0,0);
const at = (hour) => new Date(`1970-01-01T${String(hour).padStart(2,'0')}:00:00.000Z`);

describe.sequential('Phase 5 PostgreSQL patient booking', () => {
  beforeAll(async () => {
    hospital = await prisma.hospital.create({ data: { name:`Phase 5 Hospital ${tag}`,hospitalCode:`P5-${tag}`,address:'Test address',city:'Ho',region:'Volta',country:'Ghana',phone:'+233200000000',email:`p5-${tag}@example.invalid` } });
    department = await prisma.department.create({ data: { hospitalId:hospital.id,name:`Clinic ${tag}`,code:`C-${tag}`,requiresAppointment:true } });
    const doctorUser = await prisma.user.create({ data:{ email:`doctor-${tag}@example.invalid`,passwordHash:'test-hash-not-login',role:'DOCTOR' } }); userIds.push(doctorUser.id);
    doctor = await prisma.doctorProfile.create({ data:{ userId:doctorUser.id,firstName:'Ama',lastName:'Test',phone:'+233200000001',licenseNumber:`LIC-${tag}`,specialization:'General Medicine',qualification:'MBChB' } });
    await prisma.doctorHospital.create({ data:{ doctorId:doctor.id,hospitalId:hospital.id,employeeNumber:`EMP-${tag}`,startedAt:new Date('2026-01-01') } });
    await prisma.doctorDepartment.create({ data:{ doctorId:doctor.id,departmentId:department.id,hospitalId:hospital.id,primaryDepartment:true } });
    const dayOfWeek=['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'][future.getUTCDay()];
    await prisma.departmentSchedule.create({data:{hospitalId:hospital.id,departmentId:department.id,dayOfWeek,startTime:at(8),endTime:at(17),dailyCapacity:20}});
    await prisma.doctorSchedule.create({data:{hospitalId:hospital.id,departmentId:department.id,doctorId:doctor.id,dayOfWeek,startTime:at(8),endTime:at(17),consultationDurationMinutes:60,maximumPatients:8}});
    slot = await prisma.appointmentSlot.create({ data:{ hospitalId:hospital.id,departmentId:department.id,doctorId:doctor.id,date:future,startTime:at(9),endTime:at(10),capacity:1 } });
    secondSlot = await prisma.appointmentSlot.create({ data:{ hospitalId:hospital.id,departmentId:department.id,doctorId:doctor.id,date:future,startTime:at(10),endTime:at(11),capacity:1 } });
    for (const index of [1,2]) { const user=await prisma.user.create({data:{email:`patient-${index}-${tag}@example.invalid`,passwordHash:'test-hash-not-login',role:'PATIENT'}});userIds.push(user.id);const patient=await prisma.patientProfile.create({data:{userId:user.id,firstName:`Patient${index}`,lastName:'Test',dateOfBirth:new Date('1990-01-01'),gender:'PREFER_NOT_TO_SAY',phone:`+23320000000${index}`,address:'Test address',city:'Ho',region:'Volta'}});patients.push({...patient,userId:user.id});cards.push(await prisma.patientCard.create({data:{patientId:patient.id,hospitalId:hospital.id,cardType:'HOSPITAL_CARD',cardNumber:`CARD-${tag}-${index}`,verificationStatus:'VERIFIED'}})); }
  });
  afterAll(async () => {
    await prisma.auditLog.deleteMany({where:{userId:{in:userIds}}}); await prisma.notification.deleteMany({where:{userId:{in:userIds}}}); await prisma.appointment.deleteMany({where:{hospitalId:hospital?.id}}); await prisma.patientHospitalRecord.deleteMany({where:{hospitalId:hospital?.id}}); await prisma.patientCard.deleteMany({where:{hospitalId:hospital?.id}}); await prisma.appointmentSlot.deleteMany({where:{hospitalId:hospital?.id}}); await prisma.doctorSchedule.deleteMany({where:{hospitalId:hospital?.id}}); await prisma.departmentSchedule.deleteMany({where:{hospitalId:hospital?.id}}); await prisma.doctorDepartment.deleteMany({where:{hospitalId:hospital?.id}}); await prisma.doctorHospital.deleteMany({where:{hospitalId:hospital?.id}}); if(doctor)await prisma.doctorProfile.delete({where:{id:doctor.id}}); await prisma.patientProfile.deleteMany({where:{userId:{in:userIds}}}); await prisma.user.deleteMany({where:{id:{in:userIds}}}); if(department)await prisma.department.delete({where:{id:department.id}}); if(hospital)await prisma.hospital.delete({where:{id:hospital.id}}); await prisma.$disconnect();
  });
  test('patient card output is masked', () => expect(maskCardNumber('1234567890')).toMatch(/7890$/));
  test('past availability dates are rejected', () => expect(availabilitySchema.safeParse({ date: '2020-01-01' }).success).toBe(false));
  test('recommendation chooses the earliest real available slot', async () => { const result=await appointmentRecommendationService.recommend({hospitalId:hospital.id,departmentId:department.id,date:future.toISOString().slice(0,10)});expect(result.recommendedSlot.id).toBe(slot.id); });
  test('two patients cannot exceed a capacity-one slot', async () => { const attempts=await Promise.allSettled(patients.map((p,i)=>appointmentService.createPatientBooking({patientId:p.id,userId:p.userId,slotId:slot.id,patientCardId:cards[i].id,reasonForVisit:'Concurrency test'})));expect(attempts.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(attempts.filter(x=>x.status==='rejected')).toHaveLength(1);const stored=await prisma.appointmentSlot.findUnique({where:{id:slot.id}});expect(stored.bookedCount).toBe(1);expect(stored.status).toBe('FULL'); });
  test('booking derives identity and creates notification/audit', async () => { const appointment=await prisma.appointment.findFirst({where:{appointmentSlotId:slot.id}});expect(appointment.appointmentNumber).toMatch(/^APT-\d{4}-/);expect(patients.some(p=>p.id===appointment.patientId)).toBe(true);expect(await prisma.notification.count({where:{userId:{in:userIds},title:'Appointment booked'}})).toBe(1);expect(await prisma.auditLog.count({where:{action:'APPOINTMENT_CREATED',resourceId:appointment.id}})).toBe(1); });
  test('another patient cannot cancel the appointment', async () => { const appointment=await prisma.appointment.findFirst({where:{appointmentSlotId:slot.id}});const owner=patients.find(p=>p.id===appointment.patientId);const other=patients.find(p=>p.id!==owner.id);await expect(appointmentService.cancelPatientAppointment(appointment.id,other.id,other.userId)).rejects.toMatchObject({statusCode:403}); });
  test('cancellation releases capacity', async () => { const appointment=await prisma.appointment.findFirst({where:{appointmentSlotId:slot.id}});const owner=patients.find(p=>p.id===appointment.patientId);await appointmentService.cancelPatientAppointment(appointment.id,owner.id,owner.userId,'Changed plans');const stored=await prisma.appointmentSlot.findUnique({where:{id:slot.id}});expect(stored.bookedCount).toBe(0);expect(stored.status).toBe('AVAILABLE'); });
  test('reschedule reserves new slot and releases old slot atomically', async () => { const owner=patients[0];const booked=await appointmentService.createPatientBooking({patientId:owner.id,userId:owner.userId,slotId:slot.id,patientCardId:cards[0].id,reasonForVisit:'Reschedule test'});const updated=await appointmentService.reschedulePatientAppointment(booked.id,owner.id,owner.userId,secondSlot.id);expect(updated.appointmentSlotId).toBe(secondSlot.id);const [oldFresh,newFresh]=await Promise.all([prisma.appointmentSlot.findUnique({where:{id:slot.id}}),prisma.appointmentSlot.findUnique({where:{id:secondSlot.id}})]);expect(oldFresh.bookedCount).toBe(0);expect(newFresh.bookedCount).toBe(1); });
  test('pending and another-patient cards are rejected', async () => { const pending=await prisma.patientCard.update({where:{id:cards[1].id},data:{verificationStatus:'PENDING'}});await expect(appointmentService.createPatientBooking({patientId:patients[1].id,userId:patients[1].userId,slotId:slot.id,patientCardId:pending.id,reasonForVisit:'Card test'})).rejects.toMatchObject({statusCode:403});await expect(appointmentService.createPatientBooking({patientId:patients[1].id,userId:patients[1].userId,slotId:slot.id,patientCardId:cards[0].id,reasonForVisit:'Ownership test'})).rejects.toMatchObject({statusCode:400}); });
});
