import { afterAll, beforeAll, describe, expect, test } from 'vitest';
import { randomUUID } from 'node:crypto';
import prisma from '../src/config/prisma.js';
import { appointmentWorkflowService } from '../src/services/appointmentWorkflowService.js';
import { vitalService } from '../src/services/vitalService.js';
import { triageService } from '../src/services/triageService.js';
import { queueService, orderQueue } from '../src/services/queueService.js';
import { consultationService } from '../src/services/consultationService.js';
import { clinicalVitalSchema, consultationCompleteSchema } from '../src/validators/clinicalValidators.js';

const tag=randomUUID().slice(0,8),ids={users:[],hospitals:[],departments:[],appointments:[]};let hospitalA,hospitalB,departmentA,departmentB,nurse,doctorA,doctorB,patientA,patientB,appointmentA,otherHospitalAppointment;
const today=new Date();today.setUTCHours(0,0,0,0);const time=h=>new Date(`1970-01-01T${String(h).padStart(2,'0')}:00:00.000Z`);
async function user(role,label){const x=await prisma.user.create({data:{email:`p6-${label}-${tag}@example.invalid`,passwordHash:'test-only',role}});ids.users.push(x.id);return x;}
async function patient(label){const u=await user('PATIENT',label);const p=await prisma.patientProfile.create({data:{userId:u.id,firstName:label,lastName:'PhaseSix',dateOfBirth:new Date('1990-01-01'),gender:'PREFER_NOT_TO_SAY',phone:'+233200000001',address:'Test',city:'Ho',region:'Volta'}});return{...p,userId:u.id};}
async function appointment(patient,doctor,hospital,department,label,status='CONFIRMED',start=9){const a=await prisma.appointment.create({data:{appointmentNumber:`P6-${tag}-${label}`,patientId:patient.id,hospitalId:hospital.id,departmentId:department.id,doctorId:doctor.id,appointmentDate:today,startTime:time(start),endTime:time(start+1),reasonForVisit:'Phase 6 workflow test',bookingMethod:'STAFF',status}});ids.appointments.push(a.id);return a;}

describe.sequential('Phase 6 clinical workflow',()=>{
 beforeAll(async()=>{hospitalA=await prisma.hospital.create({data:{name:`Clinical A ${tag}`,hospitalCode:`CLA-${tag}`,address:'A',city:'Ho',region:'Volta',country:'Ghana',phone:'+233200001111',email:`cla-${tag}@example.invalid`}});hospitalB=await prisma.hospital.create({data:{name:`Clinical B ${tag}`,hospitalCode:`CLB-${tag}`,address:'B',city:'Accra',region:'Greater Accra',country:'Ghana',phone:'+233200002222',email:`clb-${tag}@example.invalid`}});ids.hospitals.push(hospitalA.id,hospitalB.id);departmentA=await prisma.department.create({data:{hospitalId:hospitalA.id,name:`OPD ${tag}`,code:`OPA-${tag}`}});departmentB=await prisma.department.create({data:{hospitalId:hospitalB.id,name:`OPD B ${tag}`,code:`OPB-${tag}`}});ids.departments.push(departmentA.id,departmentB.id);
 const nu=await user('NURSE','nurse');nurse=await prisma.nurseProfile.create({data:{userId:nu.id,hospitalId:hospitalA.id,employeeNumber:`N-${tag}`,firstName:'Nana',lastName:'Nurse',phone:'+233200003333',licenseNumber:`NL-${tag}`}});const du1=await user('DOCTOR','doctor-a');doctorA=await prisma.doctorProfile.create({data:{userId:du1.id,firstName:'Dela',lastName:'Doctor',phone:'+233200004444',licenseNumber:`DL1-${tag}`,specialization:'General Practice',qualification:'MBChB'}});const du2=await user('DOCTOR','doctor-b');doctorB=await prisma.doctorProfile.create({data:{userId:du2.id,firstName:'Esi',lastName:'Doctor',phone:'+233200005555',licenseNumber:`DL2-${tag}`,specialization:'General Practice',qualification:'MBChB'}});for(const d of[doctorA,doctorB]){await prisma.doctorHospital.create({data:{doctorId:d.id,hospitalId:hospitalA.id,employeeNumber:`${d.id.slice(0,5)}-${tag}`,startedAt:new Date('2026-01-01')}});await prisma.doctorDepartment.create({data:{doctorId:d.id,hospitalId:hospitalA.id,departmentId:departmentA.id}});}patientA=await patient('Akos');patientB=await patient('Kojo');appointmentA=await appointment(patientA,doctorA,hospitalA,departmentA,'A');otherHospitalAppointment=await appointment(patientB,doctorB,hospitalB,departmentB,'B');});
 afterAll(async()=>{await prisma.auditLog.deleteMany({where:{userId:{in:ids.users}}});await prisma.notification.deleteMany({where:{userId:{in:ids.users}}});await prisma.consultation.deleteMany({where:{appointmentId:{in:ids.appointments}}});await prisma.triageRecord.deleteMany({where:{appointmentId:{in:ids.appointments}}});await prisma.vitalRecord.deleteMany({where:{OR:[{appointmentId:{in:ids.appointments}},{recordedByUserId:{in:ids.users}}]}});await prisma.appointment.deleteMany({where:{id:{in:ids.appointments}}});await prisma.doctorDepartment.deleteMany({where:{doctorId:{in:[doctorA?.id,doctorB?.id].filter(Boolean)}}});await prisma.doctorHospital.deleteMany({where:{doctorId:{in:[doctorA?.id,doctorB?.id].filter(Boolean)}}});await prisma.nurseProfile.deleteMany({where:{userId:{in:ids.users}}});await prisma.doctorProfile.deleteMany({where:{userId:{in:ids.users}}});await prisma.patientProfile.deleteMany({where:{userId:{in:ids.users}}});await prisma.user.deleteMany({where:{id:{in:ids.users}}});await prisma.department.deleteMany({where:{id:{in:ids.departments}}});await prisma.hospital.deleteMany({where:{id:{in:ids.hospitals}}});await prisma.$disconnect();});
 const nurseAuth=()=>({role:'NURSE',userId:nurse.userId,user:{nurseProfile:nurse}});const doctorAuth=d=>({role:'DOCTOR',userId:d.userId,user:{doctorProfile:d}});
 test('nurse worklist is hospital scoped',async()=>{const rows=await queueService.nurse(hospitalA.id,today);expect(rows.some(x=>x.id===appointmentA.id)).toBe(true);expect(rows.some(x=>x.id===otherHospitalAppointment.id)).toBe(false)});
 test('patient cannot use a nurse-only transition',async()=>await expect(appointmentWorkflowService.transition({appointmentId:appointmentA.id,actor:{role:'PATIENT',userId:patientA.userId,user:{patientProfile:patientA}},toStatus:'CHECKED_IN'})).rejects.toMatchObject({statusCode:409}));
 test('nurse checks in confirmed appointment and timestamp is set',async()=>{const x=await appointmentWorkflowService.transition({appointmentId:appointmentA.id,actor:nurseAuth(),toStatus:'CHECKED_IN',action:'APPOINTMENT_CHECKED_IN',notify:true});expect(x.status).toBe('CHECKED_IN');expect(x.checkedInAt).toBeTruthy()});
 test('repeat or wrong-status check-in is rejected',async()=>await expect(appointmentWorkflowService.transition({appointmentId:appointmentA.id,actor:nurseAuth(),toStatus:'CHECKED_IN'})).rejects.toMatchObject({statusCode:409}));
 test('patient vitals stay PATIENT and UNVERIFIED and BMI is backend-calculated',async()=>{const v=await vitalService.create(patientA.id,{hospitalId:hospitalA.id,appointmentId:appointmentA.id,weight:70,height:175,source:'PATIENT',verificationStatus:'VERIFIED',recordedByUserId:patientA.userId});expect(v.source).toBe('PATIENT');expect(v.verificationStatus).toBe('UNVERIFIED');expect(Number(v.bmi)).toBeCloseTo(22.86,1)});
 test('nurse record forces NURSE and VERIFIED',async()=>{const v=await vitalService.createClinical(appointmentA.id,nurseAuth(),{temperature:37,heartRate:80,weight:70,height:175});expect(v.source).toBe('NURSE');expect(v.verificationStatus).toBe('VERIFIED')});
 test('nurse cannot record vitals for another hospital',async()=>await expect(vitalService.createClinical(otherHospitalAppointment.id,nurseAuth(),{temperature:37})).rejects.toMatchObject({statusCode:403}));
 test('technical vital bounds reject impossible input',()=>{expect(clinicalVitalSchema.safeParse({oxygenSaturation:500}).success).toBe(false);expect(clinicalVitalSchema.safeParse({temperature:-100}).success).toBe(false)});
 test('triage requires checked in status and derives nurse ID',async()=>{await expect(triageService.save(otherHospitalAppointment.id,nurse,{chiefComplaint:'Test',urgencyLevel:'LOW'})).rejects.toBeTruthy();const t=await triageService.save(appointmentA.id,nurse,{chiefComplaint:'Persistent fever',triageNotes:'Review promptly',urgencyLevel:'EMERGENCY'});expect(t.nurseId).toBe(nurse.id);expect(t.urgencyLevel).toBe('EMERGENCY');expect((await prisma.appointment.findUnique({where:{id:appointmentA.id}})).status).toBe('TRIAGED')});
 test('triaged appointment moves safely to waiting',async()=>{const x=await appointmentWorkflowService.transition({appointmentId:appointmentA.id,actor:nurseAuth(),toStatus:'WAITING',action:'APPOINTMENT_MOVED_TO_WAITING'});expect(x.status).toBe('WAITING')});
 test('emergency and same-priority queue ordering is deterministic',()=>{const later={id:'later',triageRecords:[{urgencyLevel:'EMERGENCY'}],triagedAt:'2026-01-01T10:00:00Z'},routine={id:'routine',triageRecords:[{urgencyLevel:'ROUTINE'}],triagedAt:'2026-01-01T08:00:00Z'},early={id:'early',triageRecords:[{urgencyLevel:'EMERGENCY'}],triagedAt:'2026-01-01T09:00:00Z'};expect(orderQueue([routine,later,early]).map(x=>x.id)).toEqual(['early','later','routine'])});
 test('doctor queue contains assigned patient only',async()=>{const rows=await queueService.doctor(doctorA.id,today);expect(rows.map(x=>x.id)).toContain(appointmentA.id);expect((await queueService.doctor(doctorB.id,today)).map(x=>x.id)).not.toContain(appointmentA.id)});
 test('unassigned doctor cannot start consultation',async()=>await expect(consultationService.start(appointmentA.id,doctorB)).rejects.toMatchObject({statusCode:403}));
 test('concurrent consultation start permits exactly one transition',async()=>{const attempts=await Promise.allSettled([consultationService.start(appointmentA.id,doctorA),consultationService.start(appointmentA.id,doctorA)]);expect(attempts.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(attempts.filter(x=>x.status==='rejected')).toHaveLength(1);expect((await prisma.appointment.findUnique({where:{id:appointmentA.id}})).status).toBe('IN_CONSULTATION')});
 test('consultation record belongs to assigned appointment and patient',async()=>{const c=await prisma.consultation.findUnique({where:{appointmentId:appointmentA.id}});expect(c.patientId).toBe(patientA.id);expect(c.doctorId).toBe(doctorA.id)});
 test('doctor saves clinician-entered diagnosis draft',async()=>{const c=await consultationService.save(appointmentA.id,doctorA,{chiefComplaint:'Persistent fever',clinicalObservations:'Alert',consultationNotes:'Reviewed',diagnosis:'Clinician-entered test diagnosis',treatmentPlan:'Test treatment plan',followUpRequired:false,followUpDate:null});expect(c.diagnosis).toBe('Clinician-entered test diagnosis')});
 test('follow-up completion validation requires a date',()=>expect(consultationCompleteSchema.safeParse({chiefComplaint:'Complaint',diagnosis:'Diagnosis',treatmentPlan:'Plan',followUpRequired:true}).success).toBe(false));
 test('doctor completes consultation with timestamps and notification',async()=>{const c=await consultationService.complete(appointmentA.id,doctorA,{chiefComplaint:'Persistent fever',clinicalObservations:'Alert',consultationNotes:'Reviewed',diagnosis:'Clinician-entered test diagnosis',treatmentPlan:'Test treatment plan',followUpRequired:true,followUpDate:'2026-12-01'});expect(c.completedAt).toBeTruthy();const a=await prisma.appointment.findUnique({where:{id:appointmentA.id}});expect(a.status).toBe('COMPLETED');expect(a.completedAt).toBeTruthy();expect(await prisma.notification.count({where:{userId:patientA.userId,title:'Consultation completed'}})).toBe(1)});
 test('completed consultation cannot restart',async()=>await expect(consultationService.start(appointmentA.id,doctorA)).rejects.toMatchObject({statusCode:409}));
 test('patient sees own safe completed summary only',async()=>{const own=await consultationService.patientSummary(appointmentA.id,patientA.id);expect(own.diagnosis).toBeTruthy();expect(own.consultationNotes).toBeUndefined();await expect(consultationService.patientSummary(appointmentA.id,patientB.id)).rejects.toMatchObject({statusCode:403})});
 test('clinical audit events were created without narratives',async()=>{const events=await prisma.auditLog.findMany({where:{userId:{in:ids.users},action:{in:['APPOINTMENT_CHECKED_IN','VITAL_RECORDED','TRIAGE_CREATED','CONSULTATION_STARTED','CONSULTATION_UPDATED','CONSULTATION_COMPLETED']}}});expect(events.length).toBeGreaterThanOrEqual(6);expect(JSON.stringify(events)).not.toContain('Clinician-entered test diagnosis')});
});
