import{describe,expect,test,vi}from'vitest';import{requestModelPrediction}from'../src/services/aiModelService.js';import{assessSymptomsHybrid}from'../src/ai/hybridAssessmentService.js';import{normalizeSymptoms}from'../src/ai/symptomNormalizer.js';
const valid={assessmentMethod:'ML_MODEL',modelVersion:'ml-logreg-v1.0',predictions:[{condition:'viral_respiratory_illness',score:.72,departmentCategory:'GENERAL'}],lowConfidence:false,confidenceThreshold:.45,message:null};
describe('Phase 7.1 Node and ML integration',()=>{
 test('valid model response is validated',async()=>expect(await requestModelPrediction({}, {fetchImpl:async()=>({ok:true,json:async()=>valid}),baseUrl:'http://model'})).toEqual(valid));
 test('unavailable model rejects for fallback handling',async()=>await expect(requestModelPrediction({}, {fetchImpl:async()=>({ok:false,status:503}),baseUrl:'http://model'})).rejects.toThrow(/503/));
 test('invalid model payload is rejected',async()=>await expect(requestModelPrediction({}, {fetchImpl:async()=>({ok:true,json:async()=>({confirmedDiagnosis:'malaria'})}),baseUrl:'http://model'})).rejects.toThrow(/invalid payload/));
 test('model timeout is surfaced',async()=>await expect(requestModelPrediction({}, {fetchImpl:()=>new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),5)),baseUrl:'http://model',timeoutMs:1})).rejects.toThrow(/timeout/));
 test.each([['My body is very hot','fever'],['My head is aching','headache'],['I am breathless','difficulty_breathing'],['My stomach hurts','abdominal_pain'],['I keep throwing up','vomiting'],['I feel very weak','weakness']])('phrase extraction maps %s', (text,key)=>expect(normalizeSymptoms(text)).toContain(key));
 test('phrase matching does not use unsafe substrings',()=>expect(normalizeSymptoms('My earphone is broken')).not.toContain('ear_pain'));
 test('red flags run before and bypass model',async()=>{const predict=vi.fn();const result=await assessSymptomsHybrid({symptomsText:'severe chest pain',symptoms:[],severity:'SEVERE'},{modelService:{predict}});expect(result.urgency).toBe('EMERGENCY');expect(predict).not.toHaveBeenCalled()});
 test('model cannot downgrade emergency',async()=>{const result=await assessSymptomsHybrid({symptomsText:'I am unconscious',symptoms:[],severity:'SEVERE'},{modelService:{predict:vi.fn().mockResolvedValue(valid)}});expect(result.urgency).toBe('EMERGENCY')});
 test('valid ML output is converted to qualitative hybrid output',async()=>{const result=await assessSymptomsHybrid({symptomsText:'cough and headache',symptoms:[],severity:'MILD'},{modelService:{predict:vi.fn().mockResolvedValue(valid)}});expect(result.assessmentMethod).toBe('ML_HYBRID');expect(result.modelVersion).toBe('ml-logreg-v1.0');expect(result.possibleConditions[0].matchStrength).toBe('HIGHER_MATCH');expect(JSON.stringify(result)).not.toMatch(/confirmedDiagnosis|72%/)});
 test('low confidence falls back to general category',async()=>{const result=await assessSymptomsHybrid({symptomsText:'weak',symptoms:[],severity:'MILD'},{modelService:{predict:vi.fn().mockResolvedValue({...valid,lowConfidence:true,predictions:[{...valid.predictions[0],score:.3}]})}});expect(result.recommendedDepartmentCategory).toBe('GENERAL');expect(result.explanation).toMatch(/not specific enough/i)});
 test('model failure preserves rule fallback',async()=>{const result=await assessSymptomsHybrid({symptomsText:'fever and headache',symptoms:[],severity:'MODERATE'},{modelService:{predict:vi.fn().mockRejectedValue(new Error('down'))}});expect(result.assessmentMethod).toBe('RULE_BASED_FALLBACK');expect(result.possibleConditions.length).toBeGreaterThan(0)});
 test('elevated supplied temperature produces fever feature',async()=>{const predict=vi.fn().mockResolvedValue(valid);await assessSymptomsHybrid({symptomsText:'headache and weakness',symptoms:[],severity:'MODERATE',temperature:39},{modelService:{predict}});expect(predict.mock.calls[0][0].symptoms.fever).toBe(true)});
});
