import{describe,expect,test,vi}from'vitest';import{detectIntent,extractDepartmentName,extractTemperature}from'../src/services/chatbot/chatbotIntentService.js';import{respondToPatient}from'../src/services/chatbot/chatbotService.js';
const auth=()=>({userId:crypto.randomUUID()}),patient={id:'patient-own'},hospitalId='11111111-1111-4111-8111-111111111111',department={id:'department-ent',hospitalId,name:'ENT',schedules:[{dayOfWeek:'THURSDAY',startTime:'1970-01-01T08:00:00Z',endTime:'1970-01-01T14:00:00Z'}]};
const tools={hospitals:vi.fn(async()=>[{id:hospitalId,name:'Test Hospital'}]),departments:vi.fn(async()=>[department]),departmentByName:vi.fn(async(_id,name)=>name==='ENT'?department:null),doctors:vi.fn(async()=>[{id:'doctor',firstName:'Ama',lastName:'Test',appointmentSlots:[{id:'slot'}]}]),appointments:vi.fn(async id=>id===patient.id?[{appointmentNumber:'APT-OWN',status:'CONFIRMED'}]:[]),cards:vi.fn(async id=>id===patient.id?[{cardType:'NHIS_CARD',maskedCardNumber:'•••• 1234',verificationStatus:'VERIFIED'}]:[]),assess:vi.fn(async()=>({id:'assessment',urgency:'MODERATE',explanation:'Preliminary match.',recommendedAction:'Arrange review.',disclaimer:'Not a diagnosis.',redFlagDetected:false,recommendedDepartment:{id:department.id,hospitalId,name:'ENT'}}))};
const ask=(message,extra={})=>respondToPatient({message,hospitalId,auth:auth(),patient,request:{},...extra},{tools});
describe('Phase 7.1 Care Assistant',()=>{
 test.each([['hospital list','HOSPITAL_LIST'],['show departments','DEPARTMENT_LIST'],['when is ENT available?','DEPARTMENT_SCHEDULE'],['which ENT doctors are free Thursday?','DOCTOR_AVAILABILITY'],['check my appointments','MY_APPOINTMENTS'],['check my card','CARD_STATUS'],['book an appointment','BOOK_APPOINTMENT'],['my temperature is 39 and I have headache','SYMPTOM_CHECK'],['what is blood pressure?','GENERAL_HEALTH_INFO'],['help','HELP']])('%s detects %s',(message,intent)=>expect(detectIntent(message)).toBe(intent));
 test('unknown intent returns safe help',async()=>expect((await ask('purple elephants')).response).toMatch(/I can show hospitals/));
 test('ENT schedule uses the controlled schedule tool',async()=>{const result=await ask('When is ENT available?');expect(tools.departmentByName).toHaveBeenCalled();expect(result.response).toMatch(/THURSDAY.*8:00.*2:00/)});
 test('doctor availability uses real availability tool contract',async()=>{const result=await ask('Which ENT doctors are free Thursday?');expect(tools.doctors).toHaveBeenCalledWith(department.id,expect.any(String));expect(result.data[0].firstName).toBe('Ama')});
 test('appointment lookup passes authenticated patient only',async()=>{await ask('check my appointments');expect(tools.appointments).toHaveBeenCalledWith(patient.id);expect(tools.appointments).not.toHaveBeenCalledWith(expect.not.stringMatching(/^patient-own$/))});
 test('card lookup passes authenticated patient and preserves masking',async()=>{const result=await ask('check my card');expect(tools.cards).toHaveBeenCalledWith(patient.id);expect(result.response).toContain('•••• 1234');expect(result.response).not.toMatch(/\d{8,}/)});
 test('symptom message invokes assessment tool',async()=>{const result=await ask('my temperature is 39 and my body is hot with headache');expect(tools.assess).toHaveBeenCalled();expect(result.response).toMatch(/Not a diagnosis/)});
 test('booking never executes and requires confirmation',async()=>{const result=await ask('book the earliest ENT doctor');expect(result.requiresConfirmation).toBe(true);expect(result.response).toMatch(/review and confirm/i)});
 test('context understands follow-up doctor question',()=>expect(detectIntent('Who is free Thursday?',{departmentId:'ent'})).toBe('DOCTOR_AVAILABILITY'));
 test('department extraction supports maternity and fertility',()=>{expect(extractDepartmentName('Maternity clinic')).toBe('Maternity');expect(extractDepartmentName('fertility services')).toBe('Fertility')});
 test('temperature extraction rejects implausible values',()=>{expect(extractTemperature('temperature is 39.0 C')).toBe(39);expect(extractTemperature('temperature is 500 C')).toBeNull()});
 test('no direct SQL or credential tool exists',()=>{expect(Object.keys(tools)).not.toContain('query');expect(JSON.stringify(tools)).not.toMatch(/password|jwt|refreshToken|DATABASE_URL/)});
 test('hospital context is required for clinical tools',async()=>{const result=await respondToPatient({message:'When is ENT available?',auth:auth(),patient,request:{}},{tools});expect(result.response).toMatch(/select a hospital/i)});
});
